/**
 * MemoQuiz API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkCreateCardItem } from './bulkCreateCardItem';


export interface BulkCreateCardsRequest { 
    cards: Array<BulkCreateCardItem>;
}

