/**
 * MemoQuiz API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionCardDto } from './sessionCardDto';


export interface SessionDto { 
    id?: number;
    startedAt?: string;
    cards?: Array<SessionCardDto>;
}

