CREATE TABLE card (
    id BIGSERIAL PRIMARY KEY,
    front VARCHAR(2000) NOT NULL,
    back VARCHAR(10000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'INACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE card_progress (
    card_id BIGINT PRIMARY KEY REFERENCES card(id) ON DELETE CASCADE,
    box SMALLINT NOT NULL DEFAULT 1 CHECK (box >= 1 AND box <= 7),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
